In [1]:
import numpy as np

In [ ]:
# padding cannot be done by right side cant be done by left side.
# numpy do not allow it.
#arr=np.arrange(24).reshape(3,4,2)
#arr1=np.arrange(12).reshape(3,4)

In [ ]:
# arr=np.arrange(12).reshape(4,-1)
# arr2=arr.reshaoe(5,-1)
# print(arr)
# print(arr.shape)

In [ ]:
import numpy as np

In [6]:
import numpy as np
arr=np.arange(10)
print(arr.shape)
arr1=arr.reshape(1,-1)
arr2=arr.reshape(-1,1)
print("row vec",arr1)
print("col",arr2)

(10,)
row vec [[0 1 2 3 4 5 6 7 8 9]]
col [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
arr=np.arange(12).reshape(4,3)
print(arr)
arr1=arr.ravel()#shallow copy
arr1[0]=99

arr2=arr.flatten()#deep copy
arr2[1]=100
print("original Array",arr1)
print("flatten array",arr2)

print ("Ravel array",arr1)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
original Array [99  1  2  3  4  5  6  7  8  9 10 11]
flatten array [ 99 100   2   3   4   5   6   7   8   9  10  11]
Ravel array [99  1  2  3  4  5  6  7  8  9 10 11]
