# NumPy Practice Session

Quick one-line recaps only — the focus here is practice. For each topic, solve the questions in the empty code cells provided.


## 1. Array Creation Basics

_`np.array(list)` → from list | `np.zeros(shape)` → all 0s | `np.ones(shape)` → all 1s | `np.full(shape, val)` → custom value | `np.arange(start,stop,step)` → like range()_


**Q1.1** Create a 1D array of 6 numbers of your choice.

In [1]:
import numpy as np

In [2]:
# Write your code here
a=np.array([9,11,18,15,17,19])
print(a);

[ 9 11 18 15 17 19]


**Q1.2** Create a 3x3 array of zeros and a 2x2 array filled with the value 7.

In [5]:
# Write your code here
a=np.zeros((3,3))
print(a);
p=np.full((2,2), 7)
print(p);


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7]
 [7 7]]


**Q1.3** Create an array of odd numbers from 1 to 21 using `arange`.

In [7]:
# Write your code here
p=np.arange(1,22,1)
print(p);




[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


## 2. Advanced Creation

_`.reshape(r,c)` → change shape | `np.linspace(start,stop,num)` → num evenly spaced values | `np.eye(n)` → n×n identity matrix_


**Q2.1** Create numbers 0 to 11 using `arange` and reshape into a 3x4 matrix.

In [12]:
# Write your code here
p=np.arange(1,13).reshape(3,4)
print(p);

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Q2.2** Generate 7 evenly spaced values between 10 and 50 using `linspace`.

In [12]:
# Write your code here
p = np.round(np.linspace(10, 50, 7),1)
print(p)

[10.  16.7 23.3 30.  36.7 43.3 50. ]


**Q2.3** Create a 5x5 identity matrix.

In [16]:
# Write your code here
p=np.arange(1,26).reshape(5,5)
print(p);


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## 3. Array Attributes

_`.shape` → dimensions tuple | `.ndim` → no. of dimensions | `.size` → total elements | `.dtype` → data type_


**Q3.1** Create a (4,3) array and print its shape, ndim, size, and dtype.

In [17]:
# Write your code here

p=np.zeros((4,3))
print("shape:",p.shape)
print("ndim:",p.ndim)
print("size:",p.size)
print("dtype",p.dtype)


shape: (4, 3)
ndim: 2
size: 12
dtype float64


**Q3.2** Create a (3,) vector and check if it's compatible for a dot product with a (5,3) matrix.

In [21]:
# Write your code here
i=np.array([1,2,3])
j=np.ones((5,3))
print("vector shape:",i.shape)
print("matrix shape:",j.shape)
print("Dot product",j@i)


vector shape: (3,)
matrix shape: (5, 3)
Dot product [6. 6. 6. 6. 6.]


## 4. Indexing & Slicing

_`arr[i]` / `arr[r,c]` → access | `arr[a:b, c:d]` → sub-matrix | `arr[::step]` → step slicing | `arr[::-1]` → reverse_


**Q4.1** Create a 4x4 array with values 1-16. Extract row 2, column 3.

In [4]:
# Write your code here
p=np.arange(1,17).reshape(4,4); 
print(p[1,2])




7


**Q4.2** From the same array, extract the sub-matrix of the first two rows and last two columns.

In [6]:
# Write your code here
sub_matrix = p[:2, -2:]
print(sub_matrix)


[[3 4]
 [7 8]]


**Q4.3** Reverse the array row-wise, then column-wise.

In [7]:
# Write your code here
row_reversed = p[::-1, :]
print(row_reversed)

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [8]:
col_reversed = p[:, ::-1]
print(col_reversed)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


**Q4.4** Print every 3rd element of a 1-20 array.

In [9]:
# Write your code here
p=np.arange(1,21)
print(p[::3])

[ 1  4  7 10 13 16 19]


## 5. Data Types & Coercion

_Mixed types auto-upcast to one common dtype | `.astype(type)` → explicit conversion_


**Q5.1** Create an array mixing ints and floats — check the resulting dtype.

In [12]:
# Write your code here
arr = np.array([1, 2.5, 3, 4.5])
print(arr)
print(arr.dtype)

[1.  2.5 3.  4.5]
float64


**Q5.2** Convert a float array [1.9, 2.5, 3.1] to integers using astype.

In [13]:
# Write your code here
arr = np.array([1.9, 2.5, 3.1])
int_arr = arr.astype(int)

print(int_arr)

[1 2 3]


## 6. Vectorized Arithmetic & Boolean Masking

_`a + b`, `a * b`, `a ** 2` → element-wise ops | `arr[arr > x]` → boolean filtering_


**Q6.1** Create two same-size arrays and compute their sum, product, and squares.

In [14]:
# Write your code here


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Sum:", a + b)
print("Product:", a * b)
print("Squares of a:", a ** 2)
print("Squares of b:", b ** 2)


Sum: [5 7 9]
Product: [ 4 10 18]
Squares of a: [1 4 9]
Squares of b: [16 25 36]


**Q6.2** Create an array of 10 random-looking numbers of your choice, then filter out only values greater than 15 using a boolean mask.

In [15]:
# Write your code here

arr = np.array([8, 21, 14, 17, 5, 25, 12, 19, 3, 16])

result = arr[arr > 15]

print(result)

[21 17 25 19 16]


## 7. Random Module

_`np.random.seed(n)` → reproducibility | `.rand()` → uniform | `.randn()` → normal | `.randint(low,high,size)` → random ints | `.choice(arr,size)` → random sample | `.shuffle(arr)` → shuffle in place_


**Q7.1** Set a seed, generate a 3x3 uniform random array, and confirm reproducibility by rerunning with the same seed.

In [ ]:
# Write your code here


 


**Q7.2** Generate 5 values from a normal distribution and 5 random integers between 1-100.

In [19]:
# Write your code here
normalvalues = np.random.normal(size=5)
randomintegers = np.random.randint(1, 101, size=5)

print("Normal values:", normalvalues)
print("Random integers:", randomintegers) 


Normal values: [-1.94692719 -1.11245012  1.41726079  0.76095693  0.63969663]
Random integers: [10 67 63 62 45]


**Q7.3** Randomly pick 3 values (no repeats) from a list of 8 items, then shuffle a 1-10 array.

In [ ]:
# Write your code here



## 8. Reduction & Axis Rules

_`.sum()` / `.mean()` / `np.median()` → aggregations | `axis=0` → column-wise | `axis=1` → row-wise_


**Q8.1** Create a 3x3 matrix. Find the total sum, sum along axis=0, sum along axis=1.

In [ ]:
# Write your code here
total_sum = np.sum(p)
sum_axis0 = np.sum(p, axis=0)
sum_axis1 = np.sum(p, axis=1)

print("Matrix:")
print(p)

print("Total sum:", total_sum)
print("Sum along axis=0:", sum_axis0)
print("Sum along axis=1:", sum_axis1) 

**Q8.2** Find the mean and median of the same matrix.

In [21]:
# Write your code here

# Calculate mean and median
mean = np.mean(p)
median = np.median(p)

print("Mean:", mean)
print("Median:", median)

Mean: 2.75
Median: 2.75


## 9. Broadcasting

_Shapes match if equal or one of them is 1 (compared right to left) | smaller array auto-expands to fit_


**Q9.1** Add a (3,3) ones matrix with a 1D array of length 3 — observe the broadcast.

In [27]:
# Write your code here
A = np.ones((3, 3))
B = np.array([1, 2, 3])
result = A + B
print("Ones matrix:")
print(A)
print("\n1D array:")
print(B)
print("\nResult:")
print(result)


Ones matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D array:
[1 2 3]

Result:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


**Q9.2** Create a row vector (1,3) and column vector (3,1), add them, and check the resulting shape.

In [30]:
# Write your code here
row = np.array([[1, 2, 3]])
column = np.array([[4],
                   [5],
                   [6]])
result = row + column
print("Row vector:")
print(row)

print("Column vector:")
print(column)

print("Result:")
print(result)

print("Result shape:", result.shape)

Row vector:
[[1 2 3]]
Column vector:
[[4]
 [5]
 [6]]
Result:
[[5 6 7]
 [6 7 8]
 [7 8 9]]
Result shape: (3, 3)


## 10. Reshaping & Dimension Expansion

_`reshape(-1, n)` → auto-calculate the other dimension | `arr[np.newaxis, :]` → row vector | `arr[:, np.newaxis]` → column vector_


**Q10.1** Create a 12-element array and reshape it using -1 so it has 4 columns.

In [31]:
# Write your code here
arr = np.array([1, 2, 3, 4, 5, 6])
result = arr.reshape(-1, 3)
print(result)
print(result.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


**Q10.2** Take a 3-element 1D array and convert it into a row vector and a column vector using np.newaxis.

In [32]:
# Write your code here
arr = np.array([1, 2, 3])
row_vector = arr[np.newaxis, :]
column_vector = arr[:, np.newaxis]
print("Original array:")
print(arr)
print("Shape:", arr.shape)

print("Row vector:")
print(row_vector)
print("Shape:", row_vector.shape)

print("Column vector:")
print(column_vector)
print("Shape:", column_vector.shape)



Original array:
[1 2 3]
Shape: (3,)
Row vector:
[[1 2 3]]
Shape: (1, 3)
Column vector:
[[1]
 [2]
 [3]]
Shape: (3, 1)


## 11. Flatten vs Ravel

_`.flatten()` → returns a copy (original safe) | `.ravel()` → returns a view (original can change too)_


**Q11.1** Create a 2D array, flatten it with both methods, modify the first element of each result, and check which one affects the original array.

In [ ]:
# Write your code here

arr = np.array([[1, 2],
                [3, 4]])
flat = arr.flatten()
flat[0] = 100
print("Original:")
print(arr)
print("Flattened:")
print(flat)


Original:
[[1 2]
 [3 4]]
Flattened:
[100   2   3   4]


## 12. Stacking & Concatenation

_`np.vstack()` → stack rows | `np.hstack()` → stack columns | `np.concatenate(axis=)` → general version_


**Q12.1** Create two 2x2 arrays. Combine them using vstack, hstack, and concatenate on both axis=0 and axis=1.

In [34]:
# Write your code here

import numpy as np

# Create two 2x2 arrays
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# vstack
v_result = np.vstack((A, B))

# hstack
h_result = np.hstack((A, B))

# concatenate along axis=0
concat_axis0 = np.concatenate((A, B), axis=0)

# concatenate along axis=1
concat_axis1 = np.concatenate((A, B), axis=1)

print("A:")
print(A)

print("B:")
print(B)

print("vstack:")
print(v_result)

print("hstack:")
print(h_result)

print("concatenate axis=0:")
print(concat_axis0)

print("concatenate axis=1:")
print(concat_axis1)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack:
[[1 2 5 6]
 [3 4 7 8]]
concatenate axis=0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=1:
[[1 2 5 6]
 [3 4 7 8]]


## 13. np.where — Conditional Logic

_`np.where(cond, a, b)` → element-wise if/else | `np.where(cond)` → returns matching indices_


**Q13.1** Create a 6-element array. Label each value 'High' or 'Low' based on a threshold using np.where.

In [ ]:
# Write your code here


**Q13.2** Use np.where (without true/false args) to find the indices of values above that threshold.

In [ ]:
# Write your code here


## 14. Matrix Operations & Transpose

_`*` → element-wise multiply | `@` / `np.dot()` → matrix multiplication | `.T` → transpose (rows ↔ cols)_


**Q14.1** Create two 2x2 matrices. Compute their element-wise product and their matrix product (using both @ and np.dot).

In [ ]:
# Write your code here
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
element_wise = A * B
matrix_product_at = A @ B
matrix_product_dot = np.dot(A, B)
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nElement-wise product:")
print(element_wise)
print("\nMatrix product using @:")
print(matrix_product_at)
print("\nMatrix product using np.dot():")
print(matrix_product_dot)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise product:
[[ 5 12]
 [21 32]]

Matrix product using @:
[[19 22]
 [43 50]]

Matrix product using np.dot():
[[19 22]
 [43 50]]


**Q14.2** Print the transpose of the first matrix.

In [3]:
# Write your code here
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]

transpose = [list(row) for row in zip(*matrix)]

print("Transpose of first matrix:")
for row in transpose:
    print(row)


Transpose of first matrix:
[1, 4]
[2, 5]
[3, 6]


---
## CRUD Operations on Arrays

_Create, Read, Update, Delete/Insert — arrays are fixed-size, so delete/insert return a new array rather than modifying in place._


## 15. CRUD — Create & Read

_Create = `np.array()`/creation helpers | Read = indexing & slicing_


**Q15.1** Create a 1D array of 8 integers and a 2D array of shape (3,3).

In [2]:
# Write your code here
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
print(b)


[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Q15.2** Read the element at index 3 from the 1D array, and the middle row from the 2D array.

In [4]:
# Write your code here
print(a[3])
print(b[1])


4
[4 5 6]


## 16. CRUD — Update

_`arr[i] = val` or `arr[slice] = val` → updates values directly (arrays are mutable)_


**Q16.1** Update index 2 of your 1D array to 100.

In [5]:
# Write your code here
a[2] = 100
print(a)


[  1   2 100   4   5   6   7   8]


**Q16.2** Update the entire second row of your 2D array to [0, 0, 0].

In [ ]:
# Write your code here
b[1] = [0, 0, 0]
print(b)


## 17. CRUD — Delete & Insert

_`np.delete(arr, idx, axis=)` → remove & return new array | `np.insert(arr, idx, val)` → insert value | `np.append(arr, val)` → add at the end_


**Q17.1** Delete the element at index 0 from your 1D array (store as a new variable).

In [ ]:
# Write your code here
c = np.delete(a, 0)
print(c)


**Q17.2** Delete the last column from your 2D array.

In [6]:
# Write your code here
d = np.delete(b, -1, axis=1)
print(d)

[[1 2]
 [4 5]
 [7 8]]


**Q17.3** Use np.append to add 99 to the end of your 1D array, and np.insert to insert 50 at index 1.

In [ ]:
# Write your code here
e = np.append(a, 99)
f = np.insert(a, 1, 50)
print(e)
print(f)


[  1   2 100   4   5   6   7   8  99]
[  1  50   2 100   4   5   6   7   8]


## 18. Combined Practice

_No new functions — just combining what's covered above_


**Q18.1** Create a 5x5 array (1-25), extract its center 3x3 block, then find the row-wise sum of that block.

In [8]:
# Write your code here
import numpy as np
arr = np.arange(1, 26).reshape(5, 5)
center = arr[1:4, 1:4]
row_sum = np.sum(center, axis=1)
print("5x5 Array:")
print(arr)
print("Center 3x3 Block:")
print(center)
print("Row-wise Sum:")
print(row_sum)


5x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Center 3x3 Block:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
Row-wise Sum:
[24 39 54]


**Q18.2** Create two 1D int arrays, stack them with vstack, add 0.5 to the result and check the dtype coercion.

In [ ]:
# Write your code here


**Q18.3** Create a 4x4 matrix with np.diag() using diagonal values 2,4,6,8, then find its transpose.

In [ ]:
# Write your code here
